---
- name: Test Playbook
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
    - name: Handler tasks
      package:
        name: httpd
        state: latest
      notify: HTTPD RESTART

    - name: Install mysql
      package:
        name: mariadb-server
        state: present
      notife: MYSQL RESTART

  handlers: 
    - name: Restart httpd
      systemd:
        name: httpd
        state: restarted 

    - name: MYSQL RESTART
      systemd:
        name: mysql
        state: restarted 